/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import montecarlo.Fila;
import montecarlo.Montecarlo;

/**
 *
 * @author Martin
 */
public class FrmBowling extends javax.swing.JFrame {

    /**
     * Creates new form FrmBowling
     */
    public FrmBowling() {
        initComponents();
        modelo.addColumn("ronda");
        modelo.addColumn("RND 1");
        modelo.addColumn("Palos Tirados en 1 Tiro");
        modelo.addColumn("RND 2");
        modelo.addColumn("Palos Tirados en 2 Tiro");
        modelo.addColumn("Puntos");
        modelo.addColumn("Puntaje Acumulado");
        btn_agregarOtro.setEnabled(false);
    }
    
    //atributos
    private DefaultTableModel modelo = new DefaultTableModel();
    private Montecarlo montecarlo;
    private LinkedList<Fila> filas = new LinkedList<>();
    private int acum = 0;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        configuracion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_desde = new javax.swing.JTextField();
        txt_hasta = new javax.swing.JTextField();
        btn_simular = new javax.swing.JButton();
        btn_agregarOtro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabla = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        configuracion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Desde");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Hasta");

        txt_desde.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_desde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_desdeKeyTyped(evt);
            }
        });

        txt_hasta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_hasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hastaKeyTyped(evt);
            }
        });

        btn_simular.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btn_simular.setText("Simular");
        btn_simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simularActionPerformed(evt);
            }
        });

        btn_agregarOtro.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btn_agregarOtro.setText("Agregar Otro");
        btn_agregarOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarOtroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configuracionLayout = new javax.swing.GroupLayout(configuracion);
        configuracion.setLayout(configuracionLayout);
        configuracionLayout.setHorizontalGroup(
            configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuracionLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(configuracionLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btn_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_agregarOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configuracionLayout.setVerticalGroup(
            configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simular)
                    .addComponent(btn_agregarOtro))
                .addGap(25, 25, 25))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("SIMULACION MONTECARLO BOWLING");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableResultados.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ronda", "RND1", "Palos Tirados en 1 Tiro", "RND 2", "Palos Tirados en 2 Tiro", "Puntos", "Puntaje Acumulado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setViewportView(jTableResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabla)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simularActionPerformed
        // TODO add your handling code here:
        
        modelo.setRowCount(0);
        
        int desde = Integer.parseInt(txt_desde.getText());
        if(desde < 0)
        {
            //DESDE NEGATIVO
            JOptionPane.showMessageDialog(this, "Ingrese Valores Positivos");
            txt_desde.requestFocusInWindow();
        }
        else
        {
            int hasta = Integer.parseInt(txt_hasta.getText());
            if(hasta < 0)
            {
                //HASTA NEGATIVO
                JOptionPane.showMessageDialog(this, "Ingrese Valores Positivos");
                txt_hasta.requestFocus();
            }
            else
            {
                
                //GENERO SIMULACION
                montecarlo = new Montecarlo(desde, hasta);
                montecarlo.armarMontecarlo();

                Object [] fila = new Object[7];
                filas = montecarlo.getFilas();
                

                for (int i = 0; i < filas.size(); i++) {

                    fila[0] = filas.get(i).getRonda()-1;
                    fila[1] = filas.get(i).getRnd1();
                    fila[2] = filas.get(i).getPalos1();
                    fila[3] = filas.get(i).getRnd2();
                    fila[4] = filas.get(i).getPalos2();
                    fila[5] = filas.get(i).getPts();
                    acum += filas.get(i).getPts();
                    fila[6] = acum; 

                    modelo.addRow(fila);
                }
                //Comentado hasta que se solucione la diferencia de puntajes
//                fila[0] = null;
//                fila[1] = null;
//                fila[2] = null;
//                fila[3] = null;
//                fila[4] = null;
//                fila[5] = null;
//                fila[6] = montecarlo.getPuntosTotal();
//                modelo.addRow(fila);

                jTableResultados.setModel(modelo);
                btn_agregarOtro.setEnabled(true);
            }    
        }
    }//GEN-LAST:event_btn_simularActionPerformed

    private void txt_desdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_desdeKeyTyped
        // TODO add your handling code here:
        btn_agregarOtro.setEnabled(false);
    }//GEN-LAST:event_txt_desdeKeyTyped

    private void btn_agregarOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarOtroActionPerformed
        // TODO add your handling code here:
        
        montecarlo.agregarUnaFila();
        
        Object [] fila = new Object[7];
        filas = montecarlo.getFilas();
        
        Fila ultima = filas.getLast();
        
        fila[0] = ultima.getRonda()-1;
        fila[1] = ultima.getRnd1();
        fila[2] = ultima.getPalos1();
        fila[3] = ultima.getRnd2();
        fila[4] = ultima.getPalos2();
        fila[5] = ultima.getPts();
        acum += ultima.getPts();
        fila[6] = acum;
        
        modelo.addRow(fila);
        
        jTableResultados.setModel(modelo);
    }//GEN-LAST:event_btn_agregarOtroActionPerformed

    private void txt_hastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hastaKeyTyped
        // TODO add your handling code here:
        btn_agregarOtro.setEnabled(false);
    }//GEN-LAST:event_txt_hastaKeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBowling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarOtro;
    private javax.swing.JButton btn_simular;
    private javax.swing.JPanel configuracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTextField txt_desde;
    private javax.swing.JTextField txt_hasta;
    // End of variables declaration//GEN-END:variables
}
